FASTFOOD/Areas/admin/Controllers/TypeController.cs
using FASTFOOD.Code;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FASTFOOD.Areas.admin.Controllers
{

    public class TypeController : Controller
    {
        fastfoodEntities db = new fastfoodEntities();
        // GET: admin/Type
        public ActionResult getListType(int? page)
        {
            //var listType = from s in db.LOAIMONANs select s;
            //return View(listType);

            if (!SessionHelper.IsAdmin()) return Redirect("/admin/Home/Index");
            if (page == null) page = 1;
            var list = (from s in db.LOAIMONANs select s).OrderBy(x => x.MSLOAI);
            int PageSize = 4;
            int PageNumber = (page ?? 1);
            return View(list.ToPagedList(PageNumber, PageSize));

        }

        public ActionResult CreateType()
        {
            if (!SessionHelper.IsAdmin()) return Redirect("/admin/Home/Index");
            return View();
        }

        [HttpPost, ActionName("CreateType")]
        [ValidateInput(false)]
        public ActionResult CreateType(LOAIMONAN loaimonan)
        {

            try
            {
                if (ModelState.IsValid)
                {

                    db.LOAIMONANs.Add(loaimonan);
                    db.SaveChanges();
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Error Save Data");
            }
            //Cập nhật lại danh sách hiển thị
            var listfood = from s in db.MONANs select s;
            return RedirectToAction("getListType");
        }
        //Chỉnh sửa thông tin món ăn
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (!SessionHelper.IsAdmin()) return Redirect("/admin/Home/Index");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIMONAN monan = db.LOAIMONANs.SingleOrDefault(s => s.MSLOAI == id);
            return View(monan);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id)
        {
            var typeUpdate = db.LOAIMONANs.Find(id);
            if (TryUpdateModel(typeUpdate, "", new string[] { "TENLOAI" }))
            {
                try
                {
                    db.Entry(typeUpdate).State = EntityState.Modified;
                    db.SaveChanges();
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Error Save Data");
                }
            }

            return RedirectToAction("getListType");
        }

        //Hiển thị thông tin một sách cần xoá

        //public ActionResult Delete(int? id)
        //{
        //    if (SessionHelper.GetSession() == null) return Redirect("/admin/Type/Delete");
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    LOAIMONAN loaimonan = db.LOAIMONANs.SingleOrDefault(n => n.MSLOAI == id);

        //    if (loaimonan == null)
        //    {
        //        Response.StatusCode = 404;
        //        return null;
        //    }
        //    var fkeyExist = db.MONANs.Any(x => x.MSLOAI == loaimonan.MSLOAI);
        //    if (fkeyExist)
        //    {
        //        TempData["alert"] = "Các sản phẩm thuộc loại này tồn tại!";
        //        return RedirectToAction("getListType");
        //    }

           
        //    db.LOAIMONANs.Remove(loaimonan);
        //    db.SaveChanges();
        //    return RedirectToAction("getListType");
        //}

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (!SessionHelper.IsAdmin()) return Redirect("/admin/Home/Index");
            LOAIMONAN loaimonan = db.LOAIMONANs.SingleOrDefault(n => n.MSLOAI == id);
            if (loaimonan == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(loaimonan);
        }

        //Xác nhận xoá
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            LOAIMONAN loaimonan = db.LOAIMONANs.SingleOrDefault(n => n.MSLOAI == id);
         

            if (loaimonan == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var fkeyExist = db.MONANs.Any(x => x.MSLOAI == loaimonan.MSLOAI);
            if (fkeyExist)
            {
                TempData["alert"] = "Các sản phẩm thuộc loại này tồn tại!";
                return RedirectToAction("getListType");
            }

            db.LOAIMONANs.Remove(loaimonan);
            db.SaveChanges();
            return RedirectToAction("getListType");
        }
    }


 

}

FASTFOOD/Areas/admin/Views/Type/CreateType.cshtml
@model FASTFOOD.LOAIMONAN

@{
    ViewBag.Title = "CreateType";


}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm loại món ăn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            Tên loại:
            <div class="col-md-4">
                @Html.EditorFor(model => model.TENLOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENLOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Thêm" class="btn btn-outline-success" />
                <a href="~/admin/Type/getListType" class="btn btn-outline-info">Trở lại</a>
            </div>


        </div>
    </div>
}

FASTFOOD/Areas/admin/Views/Type/Delete.cshtml
@model FASTFOOD.LOAIMONAN

@{
    ViewBag.Title = "Delete";
}


<h2>Are you sure you want to delete this?</h2>
<div>

    <hr />


    <table class="table"  style="width: fit-content;">
        <tr>
            <th>
                Mã số loại:
            </th>
            <td>
                @Html.DisplayFor(model => model.MSLOAI)
            </td>
        </tr>

        <tr>
            <th>
                Tên loại:
            </th>
            <td>
                @Html.DisplayFor(model => model.TENLOAI)
            </td>
        </tr>

       

    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-outline-success" /> |
            <a href="~/admin/Type/getListType" class="btn btn-outline-info">Trở lại</a>
        </div>
    }
</div>

FASTFOOD/Areas/admin/Views/Type/Edit.cshtml
@model FASTFOOD.LOAIMONAN

@{


}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sửa loại món ăn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   

        <div class="form-group">
            Tên loại:
            <div class="col-md-4">
                @Html.EditorFor(model => model.TENLOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENLOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-outline-success" />
                <a href="~/admin/Type/getListType" class="btn btn-outline-info">Trở lại</a>

            </div>
        </div>
    </div>
}

FASTFOOD/Areas/admin/Views/Type/getListType.cshtml
@*@model IEnumerable<FASTFOOD.LOAIMONAN>*@

@model PagedList.IPagedList<FASTFOOD.LOAIMONAN>
@using PagedList.Mvc;
@{
    ViewBag.Title = "getListType";
}

<h2>Danh sách loại</h2>


<div>
    @using (Html.BeginForm("CreateType", "Type", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
    {
        <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Thêm loại</button>
    }
</div>
<table class="table">
    <tr>
        <th>
            Mã số
        </th>
        <th>
            Tên loại
        </th>
        <th>Thao tác</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MSLOAI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TENLOAI)
            </td>
            <td>
                @Html.ActionLink("Sửa", "/Edit", new { id = item.MSLOAI }, new { @class = "btn btn-outline-success" }) |
                @Html.ActionLink("Xóa", "/Delete", new { id = item.MSLOAI }, new { @class = "btn btn-outline-danger" })
            </td>
        </tr>
    }

</table>
<div class="d-flex flex-row-reverse mr-5">
    @Html.PagedListPager(Model, page => Url.Action("getListType", new { page }))
</div>